### ISSUE TITLE
Did not work for me

### ISSUE THREAD

**Issue by TheJediMaster** [abhiTronix/raspberry-pi-cross-compilers#11]
I ran a script to install GCC8.2.0 and after 9 hours I ran the same commands to compile which gave me the error and it worked.  I believe your library links are not complete.

Using your method I have the following error
configure: error: No working boost sleep implementation found.

After install using the script the same install worked like a charm.  

My colleague found the same thing.

Maybe this will work for basic compliations but certainly not for ours

From my colleague
I think the links to the precompiled files are incomplete. I saw that some files in the bin folder have the same size. I tried different things without success. How many files have you in your gcc8 bin folder?"

**Comment by abhiTronix** [comment]
> I ran a script to install GCC8.2.0 and after 9 hours I ran the same commands to compile which gave me the error and it worked. I believe your library links are not complete.

@TheJediMaster **This error is not related to this repo. or GCC 8.2.0 at all.** You can check your working binaries as depicted in READMe section i.e. as follows:
```
Testing: (Post Linking)

You can check Installed versions as below:

    Native Compiler[if you DON'T followed step-6] (Raspberry pi only):
    arm-linux-gnueabihf-gcc-8.2.0 --version

    arm-linux-gnueabihf-g++-8.2.0 --version

    arm-linux-gnueabihf-gfortran-8.2.0 --version

    Native Compiler[if you followed step-6] (Raspberry pi only):
    gcc --version

    g++ --version

    gfortran --version

    Cross- Compiler (Ubuntu x64 Tested):
    arm-linux-gnueabihf-gcc --version

    arm-linux-gnueabihf-g++ --version

    arm-linux-gnueabihf-gfortran --version
```

> Using your method I have the following error
configure: error: No working boost sleep implementation found.

**This is a configure error, which is not related to compiler but due to missing dependency i.e. `boost development libraries` required by the Toolkit/Software/Code you are trying to run/install/configure.** So you can easily correct his issue by installing the required  `boost development libraries` as follows:
```
 sudo apt-get install libboost-system-dev libboost-filesystem-dev libboost-chrono-dev libboost-program-options-dev libboost-test-dev libboost-thread-dev

```
***Next time, Kindly correct this type of  simple error by googling them instead of raising issue here, Goodluck.***
