### ISSUE TITLE
What mean of --with-sysroot and --with-build-sysroot?

### ISSUE THREAD

**Issue by jackyxinli** [abhiTronix/raspberry-pi-cross-compilers#50]
What mean of --with-sysroot and --with-build-sysroot when build cross gcc of step one?
What will i get if i do not specify those two options when configure & make?
What relationship of --with-sysroot, --with-build-sysroot and $INSTALLDIR?

Hope your reply!

**Comment by abhiTronix** [comment]
> What mean of --with-sysroot and --with-build-sysroot when build cross gcc of step one?

`--with-sysroot` specifies the system root or sysroot, a temporary directory that will ultimately become the actual root directory of your operating system. Whereas,  GCC consider `--with-build-sysroot` option dir as the system root  only while building target libraries, instead of the directory specified with -`-with-sysroot`. 

> What relationship of --with-sysroot, --with-build-sysroot and $INSTALLDIR?

The option `--with-build-sysroot` option uses that sysroot for the duration of the build, but the final program does not remember it. Therefore we need `-with-sysroot` to specify the sysroot for the final program, therefore are always used together. 

Whereas  `$INSTALLDIR` is assigned to DESTDIR variable of GCC. DESTDIR is a variable prepended to each installed target file for staged installs, where the installed files are not placed directly into their expected location but are instead copied into a temporary location (DESTDIR). However, installed files maintain their relative directory structure and any embedded file names will not be modified. 

>  What will i get if i do not specify those two options when configure & make?

The default value, in case --with-sysroot is not given an argument, is ${gcc_tooldir}/sys-root. This mean you'll have hardcoded absolute paths in your final binaries, w.r.t gcc_tooldir. This will throws multiple error when used on another machine, since absolute paths will be missing from that machine.
